#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : eternalegypt
Version  : 0.0.11
Release  : 13
URL      : https://github.com/amelchio/eternalegypt/archive/v0.0.11/eternalegypt-0.0.11.tar.gz
Source0  : https://github.com/amelchio/eternalegypt/archive/v0.0.11/eternalegypt-0.0.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: eternalegypt-license = %{version}-%{release}
Requires: eternalegypt-python = %{version}-%{release}
Requires: eternalegypt-python3 = %{version}-%{release}
Requires: aiohttp
Requires: attrs
Requires: flatten_json
BuildRequires : aiohttp
BuildRequires : attrs
BuildRequires : buildreq-distutils3
BuildRequires : flatten_json

%description
# Eternal Egypt
This library piggybacks on the web interface of Netgear LTE modems to provide a simple async Python 3 API.

%package license
Summary: license components for the eternalegypt package.
Group: Default

%description license
license components for the eternalegypt package.


%package python
Summary: python components for the eternalegypt package.
Group: Default
Requires: eternalegypt-python3 = %{version}-%{release}

%description python
python components for the eternalegypt package.


%package python3
Summary: python3 components for the eternalegypt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the eternalegypt package.


%prep
%setup -q -n eternalegypt-0.0.11
cd %{_builddir}/eternalegypt-0.0.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1575558639
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/eternalegypt
cp %{_builddir}/eternalegypt-0.0.11/LICENSE.txt %{buildroot}/usr/share/package-licenses/eternalegypt/1e516e92e435cf640c534f48416dca1ddd6cefb7
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/eternalegypt/1e516e92e435cf640c534f48416dca1ddd6cefb7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
